services:

  home-radio-station:
    image: rouhim/home-radio-station
    build:
      context: .
      dockerfile: Containerfile
    environment:
      TZ: "Europe/Berlin"
      UID: "1000"
      GID: "1000"
    volumes:
      - ./database:/radio/database
      - ./music:/radio/music:ro
      - ./jingles:/radio/jingles:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  icecast:
    image: infiniteproject/icecast
    environment:
      ICECAST_SOURCE_PASSWORD: "haXX0r-Deströyer_123666_1337"
      ICECAST_ADMIN_PASSWORD: "hackme"
      ICECAST_ADMIN_USERNAME: "admin"
      ICECAST_ADMIN_EMAIL: "admin@localhost"
      ICECAST_LOCATION: "Earth"
      ICECAST_MAX_CLIENTS: "100"
      ICECAST_MAX_SOURCES: "1"
      ICECAST_PORT: "8000"
      ICECAST_PASSWORD: "hackme"
      ICECAST_HOSTNAME: "localhost"
      ICECAST_ADMIN: "admin@localhost"
    expose:
        - "8000"
    ports:
      - "0.0.0.0:9255:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"